// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARS86B0fvuJUQvP6UShbMFov8hs3siee8',
    appId: '1:155475562843:web:1cca52719d0fc5c6afca7e',
    messagingSenderId: '155475562843',
    projectId: 'crud-firestore-app-75516',
    authDomain: 'crud-firestore-app-75516.firebaseapp.com',
    storageBucket: 'crud-firestore-app-75516.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATrd8EeRYlwILsYdOE_6a0xwNBmimoU80',
    appId: '1:155475562843:android:87cede9dffbbebe3afca7e',
    messagingSenderId: '155475562843',
    projectId: 'crud-firestore-app-75516',
    storageBucket: 'crud-firestore-app-75516.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJKfGUOUIxdH0dzIr0bxRasT2hpwIsJeQ',
    appId: '1:155475562843:ios:03c10d2452316c09afca7e',
    messagingSenderId: '155475562843',
    projectId: 'crud-firestore-app-75516',
    storageBucket: 'crud-firestore-app-75516.firebasestorage.app',
    iosBundleId: 'com.example.crudFirestoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJKfGUOUIxdH0dzIr0bxRasT2hpwIsJeQ',
    appId: '1:155475562843:ios:03c10d2452316c09afca7e',
    messagingSenderId: '155475562843',
    projectId: 'crud-firestore-app-75516',
    storageBucket: 'crud-firestore-app-75516.firebasestorage.app',
    iosBundleId: 'com.example.crudFirestoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARS86B0fvuJUQvP6UShbMFov8hs3siee8',
    appId: '1:155475562843:web:5d3cef2dbac3d960afca7e',
    messagingSenderId: '155475562843',
    projectId: 'crud-firestore-app-75516',
    authDomain: 'crud-firestore-app-75516.firebaseapp.com',
    storageBucket: 'crud-firestore-app-75516.firebasestorage.app',
  );

}